; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.1 on 2025-12-25 at 01:38:38
; model printing time: 26s; total estimated time: 6m 9s
; total layer number: 42
; total filament length [mm] : 20.12
; total filament weight [g] : 0.06
; HEADER_BLOCK_END

; CONFIG_BLOCK_START
; printer_model = Bambu Lab X1 Carbon
; nozzle_diameter = 0.4
; filament_type = PLA;PETG
; filament_colour = #ECA514FF;#0000FFFF
; layer_height = 0.2
; CONFIG_BLOCK_END

; EXECUTABLE_BLOCK_START
G28
G1 Z5 F5000
G1 X10 Y10 F3000
G1 X20 Y20
G1 X30 Y30
G1 Z0.2
M104 S0
; EXECUTABLE_BLOCK_END
; filament used [mm] = 24.88
; filament used [g] = 0.07
; filament used [cm3] = 0.06
