; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.1 on 2025-12-25 at 09:12:04
; total layer number: 120
; HEADER_BLOCK_END

; EXECUTABLE_BLOCK_START
G28
G1 Z5 F5000
G1 X10 Y10 F3000
G1 X20 Y20
G1 X30 Y30
G1 X40 Y40
G1 X50 Y50
G1 Z0.2
G1 X60 Y60
G1 X70 Y70
M104 S0
M140 S0
; EXECUTABLE_BLOCK_END

; estimated printing time (normal mode) = 8m 0s
; total filament used [g] = 3.42
; total layers count = 120

; CONFIG_BLOCK_START
; printer_model = Voron 2.4 300
; nozzle_diameter = 0.4
; filament_type = PLA
; filament_colour = #00FF00
; layer_height = 0.2
; CONFIG_BLOCK_END
