; generated by PrusaSlicer 2.9.0 on 2025-02-10 at 18:03:14 UTC

; total layers count is not emitted by PrusaSlicer; total_layers stays null
M73 P0 R14
G28
G1 Z5 F5000
G1 X10 Y10 F3000
G1 X20 Y20
G1 X30 Y30
G1 X40 Y40
G1 X50 Y50
G1 Z0.2
G1 X60 Y60
M104 S0
M140 S0

; filament used [mm] = 496.91 / 1.19 / 1.49 / 0.08
; filament used [cm3] = 1.19
; total filament used [g] = 1.49
; estimated printing time (normal mode) = 13m 22s

; prusaslicer_config = begin
; layer_height = 0.2
; nozzle_diameter = 0.4
; filament_type = PLA
; printer_model = NEPTUNE3PRO
; prusaslicer_config = end
